# Generated by Django 5.0 on 2023-12-08 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiService', '0002_tags_sample'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tags',
            new_name='Tag',
        ),
    ]
