# Generated by Django 5.0.1 on 2024-02-15 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiService', '0002_sample_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='username',
            field=models.CharField(default='', max_length=50),
        ),
    ]
