# Generated by Django 5.0.3 on 2024-04-03 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiService', '0003_alter_tag_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=25),
        ),
    ]
