# Generated by Django 5.0 on 2023-12-11 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiService', '0003_rename_tags_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='description',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='sample',
            name='image',
            field=models.ImageField(blank=True, upload_to='sample_images/'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='tags',
            field=models.ManyToManyField(blank=True, to='apiService.tag'),
        ),
    ]
