# Generated by Django 5.0 on 2023-12-12 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiService', '0004_alter_sample_description_alter_sample_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='plot_image',
            field=models.ImageField(default='default_wave.webp', upload_to=''),
        ),
    ]
