# Generated by Django 5.0 on 2023-12-12 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiService', '0006_alter_sample_plot_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='plot_image',
            field=models.ImageField(default='default_wave.webp', upload_to='plots/'),
        ),
    ]
