# Generated by Django 5.0 on 2023-12-12 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiService', '0007_alter_sample_plot_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sample',
            name='plot_image',
        ),
    ]
