# Generated by Django 5.0 on 2023-12-12 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiService', '0008_remove_sample_plot_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='image',
            field=models.ImageField(default='defaults/output-10.jpeg', upload_to='sample_images/'),
        ),
    ]
