# Generated by Django 5.0 on 2023-12-12 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiService', '0009_alter_sample_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='image',
            field=models.ImageField(default='defaults/output01.jpeg', upload_to='sample_images/'),
        ),
    ]
