# Generated by Django 5.0 on 2023-12-13 16:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiService', '0010_alter_sample_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='follower_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='following',
            field=models.ManyToManyField(blank=True, related_name='following_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(default='defaults/default_profile.webp', upload_to='profile_images/'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_samples',
            field=models.ManyToManyField(blank=True, related_name='user_uploaded_samples', to='apiService.sample'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='image',
            field=models.ImageField(default='defaults/output01.webp', upload_to='sample_images/'),
        ),
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('folders', models.ManyToManyField(blank=True, related_name='inner_folders', to='apiService.folder')),
                ('samples', models.ManyToManyField(blank=True, related_name='samples_in_folder', to='apiService.sample')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
